window_title: "ML-accelerated identification of exfoliable 2D materials"
page_title: "Machine-learning accelerated identification of exfoliable two-dimensional materials"

about_section_title: "About this tool"

templates:
  how_to_cite: "how_to_cite.html"
  about: "about.html"
  select_content: "custom_select_content.html"

use_upload_structure_block: True

upload_structure_block_order: ['cif-pymatgen', 'cif-ase', 'pdb-ase', 'xyz-ase']

additional_accordion_entries:
  - header: "Acknowledgements"
    template_page: ack.html
